FROM node:alpine

WORKDIR '/app'

COPY package.json . 
RUN npm install 

#copy command here is not necessary if volumes have been used. Not a problem if it's used too. 
COPY . .   

CMD ["npm","run","start"]